---
ansible_become: yes
# Where to store build files for K3s?
k3s_build_dir: '{{ playbook_dir }}/build/k3s'
# Do you want to delete all data from emptydir volumes upon teardown?
k3s_delete_emptydir_data: no
no_proxy: ""
proxy_url: ""
