---
- name: Stat K3s {% if inventory_hostname in groups.k3s_server %}server{% else %}agent{% endif %} uninstall script
  stat:
    path: /usr/local/bin/k3s{% if inventory_hostname not in groups.k3s_server %}-agent{% endif %}-uninstall.sh
  register: k3s_uninstall_script
- block:
    - block:
        - name: Drain node
          kubernetes.core.k8s_drain:
            delete_options:
              delete_emptydir_data: '{{ k3s_delete_emptydir_data }}'
              force: yes
              ignore_daemonsets: yes
            name: '{{ inventory_hostname }}'
        - name: Delete node
          kubernetes.core.k8s:
            kind: Node
            name: '{{ inventory_hostname }}'
            state: absent
      delegate_to: localhost
      environment:
        HTTP_PROXY: '{{ proxy_url }}'
        HTTPS_PROXY: '{{ proxy_url }}'
        KUBECONFIG: '{{ k3s_build_dir }}/kubeconfig.yaml'
        NO_PROXY: '{{ no_proxy }}'
        http_proxy: '{{ proxy_url }}'
        https_proxy: '{{ proxy_url }}'
        no_proxy: '{{ no_proxy }}'
      ignore_errors: yes
      vars:
        ansible_become: no
    - name: Uninstall K3s {% if inventory_hostname in groups.k3s_server %}server{% else %}agent{% endif %}
      command: k3s{% if inventory_hostname not in groups.k3s_server %}-agent{% endif %}-uninstall.sh
  when: k3s_uninstall_script.stat.exists
