---
- name: ensure cgroup kernel params
  ignore_errors: yes
  lineinfile:
    backrefs: yes
    line: '\g<1>\g<2>'
    path: '{{ boot_directory }}/{{ item }}'
    regexp: '^(.*console=tty1)(?: cgroup_enable=memory cgroup_memory=1)?(.*)$'
  notify: require reboot
  with_items:
    - cmdline.txt
    - nobtcmd.txt
