---
- hosts: raspberry_pi_hw
  roles:
    - raspberry-pi-hw-up
- hosts: raspberry_pi_os
  roles:
    - raspberry-pi-os-up
- hosts: ubuntu
  roles:
    - ubuntu-up
- hosts:
    - raspberry_pi_os
    - ubuntu
  roles:
    - debian-up
- hosts:
    - raspberry_pi_os
  roles:
    - rpi-update-up
- hosts: k3s_server
  roles:
    - k3s-node-up
    - k3s-server-up
- hosts: k3s_agent
  roles:
    - k3s-node-up
    - k3s-agent-up
