---
- hosts: raspberry_pi_hw
  roles:
    - raspberry-pi-hw-up
- hosts: raspberry_pi_os
  roles:
    - raspberry-pi-os-up
- hosts: ubuntu
  roles:
    - ubuntu-up
- hosts:
    - raspberry_pi_os
    - ubuntu
  roles:
    - debian-up
- hosts: k3s_master
  roles:
    - k3s-master-up
  run_once: yes
- hosts: k3s_worker
  roles:
    - k3s-worker-up
