---
- name: stat k3s server uninstall script
  stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_server
- name: apply pre-server-down hooks
  changed_when: "'created' in pre_server_down.stdout or 'configured' in pre_server_down.stdout"
  local_action:
    module: 'command kubectl --kubeconfig=build/k3s-config.yaml apply --filename=hooks/{{ item }}.yaml'
    removes: 'hooks/{{ item }}.yaml' # it doesn't, but it prevents this step from running if it is
  register: pre_server_down
  vars:
    ansible_become: no
  with_items:
    - pre-master-down
    - k3s-pre-master-down
    - pre-server-down
  when: k3s_server.stat.exists
- name: drain and delete node
  local_action:
    module: shell
    _raw_params: |
      export KUBECONFIG=build/k3s-config.yaml
      kubectl drain {{ inventory_hostname }} --delete-local-data={% if delete_local_data %}true{% else %}false{% endif %} --force --ignore-daemonsets
      kubectl delete node {{ inventory_hostname }}
    removes: build/k3s-config.yaml # it doesn't, but it prevents this step from running if it is
  vars:
    ansible_become: no
  when: k3s_server.stat.exists
- name: uninstall k3s server
  command: k3s-uninstall.sh
  when: k3s_server.stat.exists
