---
- name: stat k3s server uninstall script
  stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_server
- block:
    - name: apply pre-server-down hooks
      local_action:
        module: kubernetes.core.k8s
        src: '{{ item }}'
        state: present
      vars:
        ansible_become: no
      with_fileglob:
        - hooks/pre-master-down.yaml
        - hooks/k3s-pre-master-down.yaml
        - hooks/pre-server-down.yaml
    - name: drain node
      local_action:
        module: 'command kubectl drain {{ inventory_hostname }} --delete-emptydir-data={% if k3s_delete_emptydir_data %}true{% else %}false{% endif %} --force --ignore-daemonsets'
      notify: reboot
      vars:
        ansible_become: no
    - name: delete node
      local_action:
        kind: Node
        module: kubernetes.core.k8s
        name: '{{ inventory_hostname }}'
        state: absent
      notify: reboot
      vars:
        ansible_become: no
    - name: uninstall k3s server
      command: k3s-uninstall.sh
  environment:
    KUBECONFIG: '{{ k3s_build_dir }}/kubeconfig.yaml'
  when: k3s_server.stat.exists
