---
- name: install strongswan
  apt:
    name:
      - strongswan
    update_cache: yes
  when: k3s_flannel_backend == "ipsec"
- name: install wireguard-tools
  apt:
    install_recommends: false
    name:
      - wireguard-tools
    update_cache: yes
  when: k3s_flannel_backend == "wireguard"
- name: make directory /etc/rancher/k3s
  file:
    path: /etc/rancher/k3s
    state: directory
- name: write /etc/rancher/k3s/registries.yaml
  template:
    dest: /etc/rancher/k3s/registries.yaml
    src: registries.yaml.j2
  notify: restart k3s service
  when: k3s_container_registry_mirror_urls
