---
- name: install container registry mirror configuration
  block:
    - file:
        path: /etc/rancher/k3s
        state: directory
      name: make config directory
    - template:
        dest: /etc/rancher/k3s/registries.yaml
        src: registries.yaml.j2
      name: write registries.yaml
  when: container_registry_mirror_url != None
