---
- name: make directory /etc/rancher/k3s
  file:
    path: /etc/rancher/k3s
    state: directory
- name: put /etc/rancher/k3s/registries.yaml
  template:
    dest: /etc/rancher/k3s/registries.yaml
    src: registries.yaml.j2
  when: container_registry_mirror_url != None
- name: install ipsec
  apt:
    name: strongswan
    update_cache: yes
  when: k3s_flannel_backend == 'ipsec'
- name: install wireguard-tools
  apt:
    name: wireguard-tools
    update_cache: yes
  when: k3s_flannel_backend == 'wireguard'
