---
- name: apt install <packages...>
  apt: '{{ k3s_apt }}'
  when: k3s_apt | length > 0
- name: make directory /etc/rancher/k3s
  file:
    path: /etc/rancher/k3s
    state: directory
- block:
    - name: write /etc/rancher/k3s/config.yaml
      template:
        dest: /etc/rancher/k3s/config.yaml
        src: config.yaml.j2
    - name: write /etc/rancher/k3s/registries.yaml
      template:
        dest: /etc/rancher/k3s/registries.yaml
        src: registries.yaml.j2
      when: k3s_registries | length > 0
  notify: restart k3s service
