---
- block:
    - name: Fix access To kubectl configuration
      file:
        mode: '600'
        path: '{{ k3s_build_dir }}/kubeconfig.yaml.bak'
    - name: Backup kubectl configuration
      copy:
        dest: '{{ k3s_build_dir }}/kubeconfig.yaml'
        src: '{{ k3s_build_dir }}/kubeconfig.yaml.bak'
    - name: Patch kubectl configuration
      lineinfile:
        backrefs: yes
        line: '\g<1>{{ server }}'
        mode: '600'
        path: '{{ k3s_build_dir }}/kubeconfig.yaml'
        regexp: '^(\s+server:\s*)https?://.*'
      vars:
        server: |-
          {% if k3s_url %}
          {{ k3s_url }}
          {% elif hostvars[groups.k3s_server[0]].k3s_node_ip is defined %}
          https://{{ hostvars[groups.k3s_server[0]].k3s_node_ip }}:6443
          {% elif hostvars[groups.k3s_server[0]].k3s_flannel_iface is defined %}
          https://{{ hostvars[groups.k3s_server[0]].ansible_facts[hostvars[groups.k3s_server[0]].k3s_flannel_iface].ipv4.address }}:6443
          {% else %}
          https://{{ hostvars[groups.k3s_server[0]].ansible_facts.default_ipv4.address }}:6443
          {% endif %}
  delegate_to: localhost
  vars:
    ansible_become: no
