---
- name: backup kubeconfig
  local_action:
    dest: '{{ k3s_build_dir }}/kubeconfig.yaml'
    module: copy
    src: '{{ k3s_build_dir }}/kubeconfig.yaml.bak'
  run_once: yes
  vars:
    ansible_become: no
- name: edit kubeconfig
  local_action:
    backrefs: yes
    line: '\g<1>{{ k3s_server_url }}'
    module: lineinfile
    path: '{{ k3s_build_dir }}/kubeconfig.yaml'
    regexp: '^(\s+server:\s*)https?://.*'
  run_once: yes
  vars:
    ansible_become: no
