---
- name: write k3s config
  local_action:
    module: copy
    dest: build/k3s-config.yaml
    src: build/k3s-config.yaml.bak
  run_once: yes
  vars:
    ansible_become: no
- name: edit k3s config
  local_action:
    backrefs: yes
    line: '\g<1>{{ ansible_default_ipv4.address }}\g<2>'
    module: lineinfile
    path: build/k3s-config.yaml
    regexp: '^(\s+server:\s+https?://)(?:[a-zA-Z0-9.-]+)([\W$].*)$'
  vars:
    ansible_become: no
