---
- name: backup kubeconfig
  local_action:
    dest: build/kubeconfig.yaml
    module: copy
    src: build/kubeconfig.yaml.bak
  run_once: yes
  vars:
    ansible_become: no
- name: edit kubeconfig
  local_action:
    backrefs: yes
    line: '\g<1>{{ ansible_default_ipv4.address }}\g<2>'
    module: lineinfile
    path: build/kubeconfig.yaml
    regexp: '^(\s+server:\s+https?://)(?:[a-zA-Z0-9.-]+)([\W$].*)$'
  run_once: yes
  vars:
    ansible_become: no
