---
- name: restart k3s service
  service:
    name: k3s
    state: restarted
- name: fix access to kubeconfig
  local_action:
    mode: '600'
    module: file
    path: '{{ k3s_build_dir }}/kubeconfig.yaml.bak'
  vars:
    ansible_become: no
- name: backup kubeconfig
  local_action:
    dest: '{{ k3s_build_dir }}/kubeconfig.yaml'
    module: copy
    src: '{{ k3s_build_dir }}/kubeconfig.yaml.bak'
  run_once: yes
  vars:
    ansible_become: no
- name: edit kubeconfig
  local_action:
    backrefs: yes
    line: '\g<1>{{ k3s_server_url }}'
    module: lineinfile
    mode: '600'
    path: '{{ k3s_build_dir }}/kubeconfig.yaml'
    regexp: '^(\s+server:\s*)https?://.*'
  run_once: yes
  vars:
    ansible_become: no
