---
- name: write /etc/rancher/k3s/config.yaml
  template:
    dest: /etc/rancher/k3s/config.yaml
    src: config.yaml.j2
- name: install k3s agent
  environment:
    INSTALL_K3S_VERSION: '{{ k3s_version }}'
    K3S_TOKEN: '{{ lookup("file", k3s_build_dir + "/server-token") }}'
  shell:
    cmd: curl --fail --location --silent https://get.k3s.io | sh -s - agent
    creates: /usr/local/bin/k3s-agent-uninstall.sh
