---
- name: install k3s server
  shell: |
    export INSTALL_K3S_VERSION='{{ k3s_version }}'
    curl --fail --location --silent https://get.k3s.io | sh -s server --service-node-port-range='{{ serviceNodePortRange }}'
  args:
    creates: /usr/local/bin/k3s-uninstall.sh
- name: fetch k3s config
  fetch:
    dest: build/k3s-config.yaml.bak
    flat: yes
    src: /etc/rancher/k3s/k3s.yaml
  notify:
    - write k3s config
    - edit k3s config
- name: fetch k3s token
  fetch:
    dest: build/k3s-token
    flat: yes
    src: /var/lib/rancher/k3s/server/node-token
- meta: flush_handlers
- name: apply post-master-up hooks
  changed_when: "'created' in post_master_up.stdout or 'configured' in post_master_up.stdout"
  local_action:
    module: 'command kubectl --kubeconfig=build/k3s-config.yaml apply --filename=hooks/{{ item }}.yaml'
    removes: 'hooks/{{ item }}.yaml' # it doesn't, but it prevents this step from running if it is
  register: post_master_up
  vars:
    ansible_become: no
  with_items:
    - k3s-post-master-up
    - post-master-up
