---
- block:
    - block:
        - name: Install First K3s Server
          shell:
            cmd: |-
              set -o pipefail
              curl --fail --location --show-error --silent https://get.k3s.io | exec sh -s - server
            executable: /bin/bash
          when: k3s_installed_version != k3s_version
        - name: Fetch Server Token
          fetch:
            dest: '{{ k3s_build_dir }}/server-token'
            flat: yes
            src: /var/lib/rancher/k3s/server/token
        - name: Fix Access To Server Token
          delegate_to: localhost
          file:
            mode: '600'
            path: '{{ k3s_build_dir }}/server-token'
          vars:
            ansible_become: no
        - name: Fetch kubectl Configuration
          fetch:
            dest: '{{ k3s_build_dir }}/kubeconfig.yaml.bak'
            flat: yes
            src: /etc/rancher/k3s/k3s.yaml
          notify:
            - Fix Access To kubectl Configuration
            - Backup kubectl Configuration
            - Patch kubectl Configuration
      when: inventory_hostname == groups.k3s_server[0]
    - block:
        - name: Install Remaining K3s Servers
          environment:
            K3S_TOKEN: '{{ lookup("file", k3s_build_dir + "/server-token") }}'
          shell:
            cmd: |-
              set -o pipefail
              curl --fail --location --show-error --silent https://get.k3s.io | exec sh -s - server
            executable: /bin/bash
          throttle: 1
          when: k3s_installed_version != k3s_version
      when: inventory_hostname != groups.k3s_server[0]
  environment:
    INSTALL_K3S_VERSION: '{{ k3s_version }}'
    http_proxy: '{{ proxy_url }}'
    https_proxy: '{{ proxy_url }}'
