---
- name: install k3s server
  environment:
    INSTALL_K3S_VERSION: '{{ k3s_version }}'
  shell:
    cmd: curl --fail --location --silent https://get.k3s.io | sh -s server
    creates: /usr/local/bin/k3s-uninstall.sh
- name: fetch k3s config
  fetch:
    dest: build/k3s-config.yaml.bak
    flat: yes
    src: /etc/rancher/k3s/k3s.yaml
  notify:
    - write k3s config
    - edit k3s config
- name: fetch k3s token
  fetch:
    dest: build/k3s-token
    flat: yes
    src: /var/lib/rancher/k3s/server/token
- meta: flush_handlers
- name: apply post-server-up hooks
  changed_when: "'created' in post_server_up.stdout or 'configured' in post_server_up.stdout"
  local_action:
    module: 'command kubectl --kubeconfig=build/k3s-config.yaml apply --filename=hooks/{{ item }}.yaml'
    removes: 'hooks/{{ item }}.yaml' # it doesn't, but it prevents this step from running if it is
  register: post_server_up
  vars:
    ansible_become: no
  with_items:
    - post-server-up
    - k3s-post-master-up
    - post-master-up
