---
- name: Enable Swap Space
  shell: update-rc.d dphys-swapfile enable && dphys-swapfile setup && dphys-swapfile swapon
  args:
    creates: /var/swap
- name: Make File /etc/resolv.conf Mutable
  changed_when: false
  file:
    attributes: -i
    path: /etc/resolv.conf
