---
- name: Apply Pre-Server-Down Hooks
  delegate_to: localhost
  environment:
    HTTP_PROXY: '{{ proxy_url }}'
    HTTPS_PROXY: '{{ proxy_url }}'
    KUBECONFIG: '{{ k3s_build_dir }}/kubeconfig.yaml'
    NO_PROXY: '{{ no_proxy }}'
    http_proxy: '{{ proxy_url }}'
    https_proxy: '{{ proxy_url }}'
    no_proxy: '{{ no_proxy }}'
  ignore_errors: yes
  kubernetes.core.k8s:
    src: '{{ item }}'
  run_once: yes
  with_fileglob:
    - '{{ k3s_hooks_dir }}/pre-master-down.yaml'
    - '{{ k3s_hooks_dir }}/k3s-pre-master-down.yaml'
    - '{{ k3s_hooks_dir }}/pre-server-down.yaml'
