---
- name: Check If A Reboot Is Required
  register: reboot_required
  stat:
    path: /var/run/reboot-required
- block:
    - block:
        - name: Reboot K3s And OpenVPN Servers One-By-One
          reboot: { }
          throttle: 1
        - name: Wait {{ sleep_after_reboot_seconds }} Seconds To Allow K3s And OpenVPN Servers To Restart
          pause:
            seconds: '{{ sleep_after_reboot_seconds }}'
      when: inventory_hostname in groups.k3s_server
    - name: Reboot All Other Hosts Concurrently
      reboot: { }
      when: inventory_hostname not in groups.k3s_server
  when: reboot_required.stat.exists
