---
- name: Apply Post-Server-Up Hooks
  delegate_to: localhost
  environment:
    HTTP_PROXY: '{{ proxy_url | default(omit, true) }}'
    HTTPS_PROXY: '{{ proxy_url | default(omit, true) }}'
    KUBECONFIG: '{{ k3s_build_dir }}/kubeconfig.yaml'
    NO_PROXY: '{{ no_proxy | default(omit, true) }}'
    http_proxy: '{{ proxy_url | default(omit, true) }}'
    https_proxy: '{{ proxy_url | default(omit, true) }}'
    no_proxy: '{{ no_proxy | default(omit, true) }}'
  ignore_errors: yes
  kubernetes.core.k8s:
    src: '{{ item }}'
  run_once: yes
  with_fileglob:
    - '{{ k3s_hooks_dir }}/post-server-up.yaml'
    - '{{ k3s_hooks_dir }}/k3s-post-master-up.yaml'
    - '{{ k3s_hooks_dir }}/post-master-up.yaml'
