---
#- name: add environment variable NO_PROXY
#  lineinfile:
#    line: '{{ item }}="{{ no_proxy }}"'
#    path: /etc/environment
#    regexp: '^\s*{{ item }}\s*='
#  notify: reboot
#  when: proxy_url
#  with_items:
#    - no_proxy
#    - NO_PROXY
#- name: add environment variables HTTP_PROXY and HTTPS_PROXY
#  lineinfile:
#    line: '{{ item }}="{{ proxy_url }}"'
#    path: /etc/environment
#    regexp: '^\s*{{ item }}\s*='
#  notify: reboot
#  when: proxy_url
#  with_items:
#    - http_proxy
#    - HTTP_PROXY
#    - https_proxy
#    - HTTPS_PROXY
- name: add apt proxies
  template:
    dest: /etc/apt/apt.conf.d/95proxies
    src: 95proxies.j2
  when: proxy_url
- name: update && upgrade full
  apt:
    update_cache: yes
    upgrade: full
- name: upgrade dist
  apt:
    upgrade: dist
  notify: reboot
- name: install common apt packages
  apt:
    name:
      - apt-transport-https
      - curl
      - net-tools
      - software-properties-common
      - traceroute
- name: autoremove packages
  apt:
    autoremove: yes
- name: autoclean packages
  apt:
    autoclean: yes
- block:
    - name: set hostname
      hostname:
        name: '{{ inventory_hostname }}'
    - name: set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"
    - name: set locale to {{ locale }}
      lineinfile:
        create: yes
        line: '{{ item.key }}={{ item.value }}'
        path: /etc/default/locale
        regexp: '^\s*#?\s*{{ item.key }}\s*='
      with_dict:
        LANG: '{{ locale }}'
        LC_ALL: '{{ locale }}'
  notify: reboot
