---
- name: Add APT proxies
  template:
    dest: /etc/apt/apt.conf.d/95proxies
    src: 95proxies.j2
  when: proxy_url
- name: apt-get update && apt-get dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
- name: apt-get install <packages...>
  apt:
    name:
      - apt-transport-https
      - curl
      - net-tools
      - software-properties-common
      - traceroute
- name: apt-get autoremove
  apt:
    autoremove: yes
- name: apt-get autoclean
  apt:
    autoclean: yes
- block:
    - name: Set hostname
      hostname:
        name: '{{ inventory_hostname }}'
    - name: Set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"
    - name: Generate locale {{ locale }}
      locale_gen:
        name: '{{ locale }}'
    - name: Set default locale to {{ locale }}
      template:
        dest: /etc/default/locale
        src: locale.j2
    - name: Configure web proxy
      lineinfile:
        backup: yes
        line: '{{ item.key}}="{{ item.value }}"'
        path: /etc/environment
        regexp: '^\s*#*\s*{{ item.key }}\s*=.*'
      with_dict:
        HTTP_PROXY: '{{ proxy_url }}'
        HTTPS_PROXY: '{{ proxy_url }}'
        NO_PROXY: '{{ no_proxy }}'
        http_proxy: '{{ proxy_url }}'
        https_proxy: '{{ proxy_url }}'
        no_proxy: '{{ no_proxy }}'
      when: proxy_url
  notify: Require reboot
