---
- name: add apt proxies
  template:
    dest: /etc/apt/apt.conf.d/95proxies
    src: 95proxies.j2
  when: proxy_url
- name: apt-get update && apt-get dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
- name: apt install <packages...>
  apt:
    name:
      - apt-transport-https
      - curl
      - net-tools
      - software-properties-common
      - traceroute
- name: apt autoremove
  apt:
    autoremove: yes
- name: apt autoclean
  apt:
    autoclean: yes
- block:
    - name: set hostname
      hostname:
        name: '{{ inventory_hostname }}'
    - name: set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"
    - name: generate locale {{ locale }}
      locale_gen:
        name: '{{ locale }}'
    - name: set default locale to {{ locale }}
      template:
        dest: /etc/default/locale
        src: locale.j2
  notify: require reboot
# See https://docs.k3s.io/advanced#additional-preparation-for-debian-buster-based-distributions :
- name: flush iptables
  iptables:
    flush: yes
- name: use iptables-legacy
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
- name: use ip6tables-legacy
  alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy
