---
#- name: add environment variable NO_PROXY
#  lineinfile:
#    line: '{{ item }}="{{ no_proxy }}"'
#    path: /etc/environment
#    regexp: '^\s*{{ item }}\s*='
#  notify: reboot
#  when: proxy_url
#  with_items:
#    - no_proxy
#    - NO_PROXY
#- name: add environment variables HTTP_PROXY and HTTPS_PROXY
#  lineinfile:
#    line: '{{ item }}="{{ proxy_url }}"'
#    path: /etc/environment
#    regexp: '^\s*{{ item }}\s*='
#  notify: reboot
#  when: proxy_url
#  with_items:
#    - http_proxy
#    - HTTP_PROXY
#    - https_proxy
#    - HTTPS_PROXY
- name: add apt proxies
  template:
    dest: /etc/apt/apt.conf.d/95proxies
    src: 95proxies.j2
  when: proxy_url
- name: update && upgrade full
  apt:
    update_cache: yes
    upgrade: full
- name: upgrade dist
  apt:
    upgrade: dist
  notify: reboot
- name: install common apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - net-tools
      - software-properties-common
      - traceroute
- name: autoremove packages
  apt:
    autoremove: yes
- name: autoclean packages
  apt:
    autoclean: yes
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
- name: "set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  notify: restart cron
- name: "set LC_ALL to {{ locale }}"
  lineinfile:
    line: 'LC_ALL={{ locale }}'
    path: /etc/default/locale
    regexp: '^\s*#?\s*LC_ALL\s*='
  notify: reboot
- name: "set LANG to {{ locale }}"
  lineinfile:
    line: 'LANG={{ locale }}'
    path: /etc/default/locale
    regexp: '^\s*#?\s*LANG\s*='
  notify: reboot
