---
- name: add apt proxies
  template:
    dest: /etc/apt/apt.conf.d/95proxies
    src: 95proxies.j2
  when: proxy_url
- name: apt update && apt full-upgrade
  apt:
    update_cache: yes
    upgrade: full
- name: apt dist-upgrade
  apt:
    upgrade: dist
  notify: reboot
- name: apt install <common packages...>
  apt:
    name:
      - apt-transport-https
      - curl
      - net-tools
      - software-properties-common
      - traceroute
- name: apt autoremove
  apt:
    autoremove: yes
- name: apt autoclean
  apt:
    autoclean: yes
- block:
    - name: set hostname
      hostname:
        name: '{{ inventory_hostname }}'
    - name: set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"
    - name: set locale to {{ locale }}
      lineinfile:
        create: yes
        line: '{{ item.key }}={{ item.value }}'
        path: /etc/default/locale
        regexp: '^\s*#?\s*{{ item.key }}\s*='
      with_dict:
        LC_ALL: '{{ locale }}'
        LC_CTYPE: '{{ locale }}'
  notify: reboot
